version: "3.5"

services:

  flash80:
    image: library/openjdk:15-jdk
    volumes:
      - './flash80/target/flash80-0.0.1-SNAPSHOT.jar:/opt/flash80/flash80.jar'
      - './data/GeoIP2-City.mmdb:/opt/flash80/GeoIP2-City.mmdb'
    command: [ 'java','-jar','/opt/flash80/flash80.jar' ]
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    #restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "2"

networks:
  default: