server:
  http:
    port: 80
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:flash80.p12
    key-store-password: flash80
    key-alias: flash80
flash80:
  cache:
    cronmilliseconds: 60000
    minutes: 0
    hours: 24
    limit: 1000
    geo:
      continent: true
      country: true
      region: true
    site: true
    uri: true
    requestParams: true
  timeoutSeconds: 10
  excludes:
    urls:
      - ^[^.]+$
      - backend
      - wp-admin
      - wp-login
    headers:
      - logged_in
      - wp_logged_in
    cookies:
      - logged_in
      - wp_logged_in
  includes:
    urls:
      - .*
    headers:
    cookies:
  hosts:
    - host: 216.58.209.46
      httpPort: 80
      httpsPort: 443
      sites:
        - google.com
        - youtube.com
    - host: 31.13.86.36
      httpPort: 80
      httpsPort: 443
      sites:
        - facebook.com