server:
  http:
    port: 80
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:flash80.p12
    key-store-password: flash80
    key-alias: flash80
flash80:
  timeoutSeconds: 10
  excludes:
    - .
  includes:
    - /
  hosts:
    - host: 123.123.123.123
      httpPort: 80
      httpsPort: 443
      sites:
        - google.com
        - youtube.com
    - host: 99.1.1.12
      httpPort: 80
      httpsPort: 443
      sites:
        - facebook.com
        - github.com