server:
  http:
    port: 80
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:flash80.p12
    key-store-password: flash80
    key-alias: flash80
flash80:
  timeoutSeconds: 10
  excludes:
    - .
  includes:
    - /
  hosts:
    - host: 216.58.209.46
      httpPort: 80
      httpsPort: 443
      sites:
        - google.com
        - youtube.com
    - host: 31.13.86.36
      httpPort: 80
      httpsPort: 443
      sites:
        - facebook.com