logging:
  level:
    org:
      kryptonmlt: debug
server:
  http:
    port: 80
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:flash80.p12
    key-store-password: flash80
    key-alias: flash80
flash80:
  purgers:
    - 127.0.0.1
    - localhost
  geodb: "/opt/flash80/GeoIP2-City.mmdb"
  cache:
    cronmilliseconds: 60000
    minutes: 0
    hours: 24
    limit: 1000
    geo:
      continent: true
      country: true
      region: true
    device: true
    browser: false
    site: true
    uri: true
    requestParams: true
  timeoutSeconds: 10
  excludes:
    urls:
      - '[.]{1}[\da-zA-Z]{3}$'
      - 'backend'
      - 'wp-admin'
      - 'wp-login'
    headers:
      - logged_in
      - wp_logged_in
    cookies:
      - logged_in
      - wp_logged_in
  includes:
    urls:
      - .*
    headers:
    cookies:
  hosts:
    - host: 192.0.78.9
      httpPort: 80
      httpsPort: 443
      sites:
        - wordpress.com
    - host: 91.198.174.192
      httpPort: 80
      httpsPort: 443
      sites:
        - wikipedia.com
        - testing.com